### ISSUE TITLE
myvect.c

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#11]
qui invece manca l'inclusione di random.h

inoltre non ti è chiaro il concetto di inizializzazione del modulo:
myvect_init() inizializza il modulo
myvect_init_in_range() può lavorare perché il modulo è stato già inizializzato

**Comment by TeoColuccio** [comment]
e quindi myvect_init() cosa fa?

**Comment by FabioZTessitore** [comment]
Tutto ciò che è necessario affinché le restanti funzioni del modulo
funzionino correttamente. Ricordi guess?

Il 24 feb 2017 7:35 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Fatto

2017-02-25 9:21 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
fatto è una parola grossa ... cerca di non essere superficiale

**Comment by FabioZTessitore** [comment]
riga 13. Me la spieghi?

**Comment by TeoColuccio** [comment]
Bhoo

**Comment by TeoColuccio** [comment]
Prof acceleriamo un po'
