### ISSUE TITLE
modulo math

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#13]
crea un nuovo modulo `myvect_math` contenente le funzioni:

myvect_math_sum();
myvect_math_mean();

usa il modulo per calcolare la media degli elementi di un vettore di interi

**Comment by TeoColuccio** [comment]
Fatto, ma non riesco ad aggiungerlo nel cmake generale..

2017-02-27 17:11 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
perché? ti si è bloccata la tastiera?

**Comment by TeoColuccio** [comment]
No perché un terzo modulo non l'ho mai aggiunto. Mi può dare una mano?

2017-02-27 19:20 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
non capisco cosa non riesci. il fatto che siano 3 non cambia niente. devi mettere le dipendenze come ti ho fatto vedere

**Comment by TeoColuccio** [comment]
A me sembra di averlo fatto

2017-02-27 20:09 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by TeoColuccio** [comment]
Ho creato un file Cmake nel modulo, composto solo da add_library perché non
necessita di altri moduli, poi ho aggiunto la subdirectory nel Cmake
generale. Cosa mi manca??

Il giorno 27 febbraio 2017 20:22, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ho aggiunto dei suggerimenti, fai pull

**Comment by TeoColuccio** [comment]
Prof allora?

Il lunedì 27 febbraio 2017, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Hai visto i suggerimenti?

**Comment by TeoColuccio** [comment]
Ma li ho pure seguiti

**Comment by FabioZTessitore** [comment]
Ma la funzione della media ha errori

**Comment by TeoColuccio** [comment]
Vabbè era cosa da niente..

Il giovedì 2 marzo 2017, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
C'è ancora un errore. Hai fatto qualche test per verificare il risultato?

**Comment by TeoColuccio** [comment]
Chiudiamo?

**Comment by TeoColuccio** [comment]
Prof ci siete?
