### ISSUE TITLE
prodotto scalare

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#14]
aggiungi la funzione `myvect_math_dot_product()` al modulo `myvect_math`
che calcola il prodotto scalare tra due vettori della stessa dimensione

**Comment by FabioZTessitore** [comment]
Non ti è chiaro come si fa il prodotto scalare

**Comment by TeoColuccio** [comment]
L'indice i del primo per l'indice i del secondo, e poi i+1 ecc.

**Comment by FabioZTessitore** [comment]
ho capito cosa hai fatto nel codice, ma non si fa così il prodotto scalare (manca qualcosa)

**Comment by FabioZTessitore** [comment]
Ora va bene. Resta il dubbio sulle due variabili size. Io il controllo lo farei prima di chiamare la funzione e non dentro
