### ISSUE TITLE
maiuscolo minuscolo

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#15]
Data una stringa, se non contiene numeri stampare tutto in maiuscolo
altrimenti stampare tutto in minuscolo (mantenere i numeri)

**Comment by TeoColuccio** [comment]
Sarai curioso di vedere il suo algoritmo.. Io meno di due cicli non posso usare: il primo per il controllo e il secondo per la stampa.

**Comment by TeoColuccio** [comment]
E poi non ho capito bene una cosa: 
- char stringa[]; E' una stringa 
- char *stringa[]; E' un puntatore a stringa 

Qual'è la differenza??

**Comment by FabioZTessitore** [comment]
char stringa[]; /* stringa */
char *stringa; /* puntatore */

**Comment by TeoColuccio** [comment]
Eh ma in cosa si differiscono? 
Char *stringa[] allora cos'è??

**Comment by TeoColuccio** [comment]
Chiudiamo?

2017-03-14 19:44 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ho caricato la mia versione

**Comment by TeoColuccio** [comment]
In pratica il vostro programma sarebbe il mio, ma semplificato in funzioni..
