### ISSUE TITLE
converte

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#16]
inserire tre caratteri cifra in una stringa
e convertirla in intero. poi fare cast a double,
infine trasformare in una stringa e stampare

**Comment by TeoColuccio** [comment]
Non credo volevate una cosa del genere... Spiegatemi meglio per favore.

**Comment by FabioZTessitore** [comment]
va quasi bene però devi memorizzare i vari dati convertiti. Ovviamente l'ultimo passaggio, da double a stringa è quello chiave dell'esercizio

**Comment by FabioZTessitore** [comment]
ps. visto che il programma è semplice semplice, almeno un Makefile mettilo

**Comment by TeoColuccio** [comment]
Come si fa a convertire da double a stringa?? Non ho trovato nessuna funzione

**Comment by FabioZTessitore** [comment]
Hehe, la stessa risposta di tazza. Guarda bene e soprattutto ragiona

Il 16 mar 2017 1:02 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Eh ma c'è poco da ragionare... indizio??

**Comment by FabioZTessitore** [comment]
Cerca cerca.

Il 16 mar 2017 5:55 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Sì ma cosa?!

**Comment by FabioZTessitore** [comment]
Come trasformare un double in una stringa

Il 16 mar 2017 5:58 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ehh vabbè.. ma c'è una funzione?? Io non trovo nulla

**Comment by FabioZTessitore** [comment]
Stai leggendo il capitolo delle stringhe?

Il 16 mar 2017 6:22 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Eh sì ma non mi sembra che ci sia qualcosa a riguardo..

**Comment by FabioZTessitore** [comment]
Cerca meglio

Il 16 mar 2017 6:57 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Prof a che pagina?? Tanto abbiamo entrambi la 3* edizione ahah perché io non ho trovato ancora nulla

**Comment by FabioZTessitore** [comment]
quale capitolo stai studiando?

**Comment by TeoColuccio** [comment]
Sempre quello delle stringhe, per risolvere l'esercizio.

**Comment by TeoColuccio** [comment]
Per favore prof. Datemi la pagina e togliamo di mezzo quest'esercizio.

Il venerdì 17 marzo 2017, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
cap 8. C'è un esercizio che fa proprio quello che ti serve

**Comment by TeoColuccio** [comment]
Sto da sempre leggendo il cap 8..

2017-03-17 20:09 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ancora non ti è chiara la faccenda ... non ci entra in quel vettore

**Comment by TeoColuccio** [comment]
Ma così usa sprintf il libro..

Il sabato 18 marzo 2017, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
è il vettore di caratteri che è troppo piccolo

**Comment by TeoColuccio** [comment]
Ora ho creato un'altra stringa con la dimensione che voglio io.. ma non mi trovo, perchè ho dato una dimensione sbagliata.. Ho dato 5 elementi, ma ce ne vanno 4 perché c'è il terminatore. Quindi perché mi ha comunque scritto tutti e 5 le cifre??

**Comment by TeoColuccio** [comment]
Forse perché non li mette in celle diverse, ma fa tutto un elemento. stringa[7788727, "\0"] e non stringa[7, 7, 8 ecc]

**Comment by FabioZTessitore** [comment]
Stai scrivendo in memoria fuori dall'array

Il 19 mar 2017 5:42 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
E come faccio per scrivere nell'array allora??

**Comment by FabioZTessitore** [comment]
Lo devi fare della dimensione giusta

Il 19 mar 2017 6:36 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Però perché un vettore di una determinata dimensione, se riceve più elementi di quanti previsti, non invande altra memoria e la stringa sí?

**Comment by FabioZTessitore** [comment]
E chi l'ha detto che non puoi sforare?

Il 20 mar 2017 7:37 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Sinceramente non ho mai provato... ok allora mi torna tutto.

Ps il programma per le password
