### ISSUE TITLE
parole

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#19]
data una stringa estrarre e stampare le parole

**Comment by TeoColuccio** [comment]
Non ho capito una cosa.. Perchè dalla seconda volta che uso strtok() gli devo passare NULL  e non di nuovo la stringa??

**Comment by FabioZTessitore** [comment]
È il modo che hanno usato per far capire alla funzione che vuoi la prossima
parola. Mentre se passi la stringa resetti e inizi da capo

Il 26 mar 2017 12:51 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Mha.. per me non ha senso

**Comment by FabioZTessitore** [comment]
E fatti la tua strtok haha

Il 26 mar 2017 2:07 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ahahaha sì lo farò.
