### ISSUE TITLE
dado

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#2]
lancia un dado a 6 facce 30000 volte e memorizza le occorrenze in un vettore
poi stampa le occorrenze e le frequenze (comparando con la frequenza teorica)

**Comment by FabioZTessitore** [comment]
Spiegami la presenza della variabile conta

Poi sostituisci il ciclo while con un for (sai già quante volte lanciare)

**Comment by TeoColuccio** [comment]
Giusto per essere più precisi: quand'è che non si sa il numero per il ciclo e quindi usiamo il while?

**Comment by FabioZTessitore** [comment]
Quando non conti un certo numero di volte, ma finché non succede qualcosa

Il 28 gen 2017 1:07 AM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Okk

**Comment by TeoColuccio** [comment]
Prof chiudiamo?

**Comment by FabioZTessitore** [comment]
ma no, comincia a far sparire quell'inutile switch

**Comment by TeoColuccio** [comment]
E che ci metto??

**Comment by FabioZTessitore** [comment]
Non serve

**Comment by TeoColuccio** [comment]
Serve un controllo..

Il lunedì 30 gennaio 2017, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non è vero

Il lunedì 30 gennaio 2017, Teodoro <notifications@github.com> ha scritto:
