### ISSUE TITLE
Ordinamento Vettori

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#20]
Il metodo piu' semplice (e meno efficiente) per
riordinare gli elementi di un vettore e' il
cosiddetto bubble sort o ordinamento a bolle.
L'algoritmo consiste nello scorrere gli elementi del vettore
e se l'elemento corrente risulta maggiore del successivo
vengono invertite le loro posizioni.
Alla fine del primo passaggio l'elemento maggiore sara' in fondo.
Il procedimento viene ripetuto fino ad ottenere
l'ordinamento di tutto il vettore.

vedi file bubble_sort/bubble_sort.c

**Comment by TeoColuccio** [comment]
Ok facile
