### ISSUE TITLE
bubble sort migliorato

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#21]
![es6_11](https://cloud.githubusercontent.com/assets/3002194/24376538/7f78ec6a-133c-11e7-9016-284e2a1ed1a2.png)

**Comment by FabioZTessitore** [comment]
non va bene nessuna delle due soluzioni

**Comment by TeoColuccio** [comment]
Io non ho capito bene il senso dei passaggi.. 
`    for (i=0; i<size-1; i++) {
      if (v[i] > v[i+1]) {
        temp = v[i];
        v[i] = v[i+1];
        v[i+1] = temp;
      }
    }
`
Questo codice non dovrebbe già controllare ogni elemento e nel caso scambiarlo??

**Comment by FabioZTessitore** [comment]
Prova a farlo a mano con un vett di quattro elementi 7 3 2 1

Il 9 apr 2017 5:47 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
A mano si trova..

**Comment by FabioZTessitore** [comment]
Metti una stampa di pass nel ciclo esterno e una di i nel ciclo interno e vediamo se il risultato è quello atteso

**Comment by TeoColuccio** [comment]
Ora dovrebbe andare...

**Comment by FabioZTessitore** [comment]
non hai caricato niente

**Comment by TeoColuccio** [comment]
Nono c'è il commit e9b404b.

**Comment by FabioZTessitore** [comment]
Metti una stampa di i nel ciclo interno e vediamo se il risultato è quello atteso
Secondo me fai una iterazione in più

**Comment by TeoColuccio** [comment]
Se ho capito bene, ora dovrebbe andare..

**Comment by FabioZTessitore** [comment]
se ti fossi preso la briga di stampare la i ti saresti accorto di aver peggiorato la situazione

**Comment by TeoColuccio** [comment]
No forse ho provato la stampa nel posto sbagliato..


2017-04-14 18:07 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ora va bene
