### ISSUE TITLE
Ricerca binaria

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#23]

**Comment by TeoColuccio** [comment]
Prof. Attendo istruzioni.

**Comment by TeoColuccio** [comment]
Non capisco perché quando ritorna -1 va in errore...

**Comment by FabioZTessitore** [comment]
non va bene

**Comment by TeoColuccio** [comment]
Perché? Ho provato, e funziona bene.

**Comment by FabioZTessitore** [comment]
Sarà un caso

Il 1 giu 2017 5:09 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
No. Tutti i casi.. Non trovo l'errore..

**Comment by FabioZTessitore** [comment]
Si confondono gli elementi del vettore con gli indici

Il 1 giu 2017 6:14 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Stampa i valori low, high e vedi se sono quelli che ti aspetti

Il 1 giu 2017 6:16 PM, "Fabio Z Tessitore" <fabioztessitore@gmail.com> ha
scritto:

**Comment by TeoColuccio** [comment]
Eh infatti... ora non riesco ad uscirne..

**Comment by FabioZTessitore** [comment]
Fallo a mano

Il 1 giu 2017 7:51 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Sì fatto. Ora dovrebbe andare

**Comment by FabioZTessitore** [comment]
Va quasi bene, controlla se riesce a beccare anche il primo e l'ultimo
elemento

Il 1 giu 2017 8:17 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Prova a creare un vettore con numeri scelti da te e vedi se li trova tutti

Il 1 giu 2017 8:20 PM, "Fabio Z Tessitore" <fabioztessitore@gmail.com> ha
scritto:

**Comment by TeoColuccio** [comment]
Pare che funziona anche con il primo e l'ultimo...

**Comment by FabioZTessitore** [comment]
E con gli altri?

Il 1 giu 2017 8:44 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ora va tutto.

**Comment by FabioZTessitore** [comment]
Ok

Il 3 giu 2017 7:07 PM, "Teodoro" <notifications@github.com> ha scritto:

Ora va tutto.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Teodoro777/vettori/issues/23#issuecomment-305988299>,
or mute the thread

**Comment by FabioZTessitore** [comment]
Il programma funziona, ma dovresti fare un aggiustamento. Non ha senso che chi chiama la funzione di ricerca debba indicare i due indici (tra l'altro `low` è sempre `0`).

In altre parole dovresti avere la funzione:

```c
int ricerca_binaria(int x, int v[], int size);
```

che al suo interno chiama la tua funzione (che rinominerai `ricerca_binaria_helper()`) con i parametri opportuni.
Tutto chiaro?
