### ISSUE TITLE
random

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#3]
Il modulo random

**Comment by FabioZTessitore** [comment]
metti il modulo random in una directory random

**Comment by FabioZTessitore** [comment]
correggi il nome del file. Deve essere CMakeLists.txt

visto che random non dipende da nessuno deve contenere una solo linea che indica quali sono i file da tenere d'occhio:
```
add_library(Random random.c random.h
```

D'ora in avanti ti riferirai al modulo random con il nome `Random`

**Comment by TeoColuccio** [comment]
E' proprio così o vi siete mangiato una parentesi?
E ora?

2017-01-30 14:37 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Mangiata

Il 30 gen 2017 9:34 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
E ora?

2017-01-30 21:47 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
