### ISSUE TITLE
dado

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#4]
facciamo un modulo dado.
Quali funzioni metteresti?

**Comment by TeoColuccio** [comment]
Io metterei una funzione che lancia il dado che ritorna il valore, una che
controlla il valore ritornato dalla funzione precedente e una per la stampa
finale.

2017-01-26 13:10 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Quella che controlla non ho capito cosa dovrebbe controllare

Quella di stampa direi proprio di no

Il 26 gen 2017 7:50 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Controlla il numero estratto ed aggiorna il vettore.. e poi perché non potrei stampare anche con quel modulo?!

**Comment by FabioZTessitore** [comment]
Perché non è responsabilità di un dado contare quante volte esce una certa
faccia

Il 26 gen 2017 10:27 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
metti il modulo dado in una directory dado

**Comment by FabioZTessitore** [comment]
aggiusta il nome del file.

per il contenuto, anche qui serve una linea:
```
add_library (Dado dado.c dado.h)
```

però non basta. Prima di tutto, qui hai un `#include "random.h"` ma il file random.h non si trova nella directory di dado. Allora bisogna dire dove cercarlo:
```
include_directories (../random)
```

Infine, siccome il modulo Dado per poter funzionare ha bisogno del modulo Random, bisogna collegare le librerie:
```
target_link_libraries (Dado Random)
```

Il file completo sarà:
```
include_directories (../random)

add_library (Dado dado.c dado.h)

target_link_libraries (Dado Random)
```

**Comment by TeoColuccio** [comment]
Fatto
