### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#5]
resta da fare il CMakeLists.txt del progetto

La prima riga specifica la versione minima di cmake da utilizzare
```
cmake_minimum_required (VERSION 2.6)
```

Poi si può dare un nome al progetto
```
project (LanciaDado)
```

Le directory in cui cercare i file .h (nel main hai solo dado.h)
```
include_directories (dado)
```

Le directory da compilare:
```
add_subdirectory (random)
add_subdirectory (dado)
```

L'eseguibile (equivalente a add_library che hai messo nei moduli)
```
add_executable (LanciaDado lancia_dado.c)
```

Infine il link delle librerie (LanciaDado dipende solo da Dado)
```
target_link_libraries (LanciaDado Dado)
```

### file completo:
```
cmake_minimum_required (VERSION 2.6)
project (LanciaDado)

include_directories (dado)

add_subdirectory (random)
add_subdirectory (dado)

add_executable (LanciaDado lancia_dado.c)
target_link_libraries (LanciaDado Dado)
```

**Comment by FabioZTessitore** [comment]
per compilare crea una cartella build, entra dentro e lancia i comandi cmake ../ e make

```
mkdir build
cd build
cmake ../
make
```

**Comment by TeoColuccio** [comment]
Errore: 
CMake Error at CMakeLists.txt:10 (target_link_libraries):
Cannot specify link libraries for target "LanciaDado" which is not built
by
this project.


2017-01-31 10:41 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Stai attento a maiuscole e minuscole

**Comment by TeoColuccio** [comment]
Ahah ok, ora dice che non trova il file lancia_dado.c
In effetti non esiste quel file..

**Comment by TeoColuccio** [comment]
Ora il problema è alla riga successiva

2017-02-01 23:54 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
il tuo file si chiama main.c

**Comment by TeoColuccio** [comment]
Chiudiamo??
