### ISSUE TITLE
dadi

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#6]
Due dadi

**Comment by FabioZTessitore** [comment]
in attesa

**Comment by TeoColuccio** [comment]
Così mi sembra un pò troppo facile..

2017-02-09 14:03 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by TeoColuccio** [comment]
Comunque il gitignore c'è, ma non si vede..

**Comment by FabioZTessitore** [comment]
Gitignore Lo devi mettere in dado e comunque lo hai scritto male (solo build/)

Riguardo ai dadi, non hai capito cosa fare. Devi trovare le frequenze lanciando due dadi

**Comment by TeoColuccio** [comment]
Perché ora che sto facendo?

Il venerdì 10 febbraio 2017, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Li stai lanciando ma non c'è relazione tra i due. Se uno ti dice di lanciare due dadi fai così?

**Comment by TeoColuccio** [comment]
Non capisco.. Che relazione ci dovrebbe stare?

Il venerdì 10 febbraio 2017, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Ma se uno ti chiede di lanciare due dadi, cosa fai?

**Comment by TeoColuccio** [comment]
Lancio due dadi

2017-02-10 23:20 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by TeoColuccio** [comment]
Ecco le combinazioni che ho trovato:
2: 1+1; 1+1; 
3: 2+1; 1+2 
4: 3+1; 2+2; 2+2; 1+3;
5: 4+1; 3+2; 2+3; 1+4; 
6: 5+1; 4+2; 3+3; 3+3; 2+4; 1+5;
7: 6+1; 5+2; 4+3; 3+4; 2+5; 1+6;
8: 6+2; 5+3; 4+4; 4+4; 3+5;
9: 6+3; 5+4; 4+5; 3+6; 
10: 6+4; 5+5; 5+5; 4+6;
11: 6+5; 5+6;  
12: 6+6; 6+6;

**Comment by FabioZTessitore** [comment]
Devi calcolare e mettere nel codice per verificare se la simulazione dà
risultati esatti

Il 11 feb 2017 7:05 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ho fatto un bel "ingiarmone"!

**Comment by FabioZTessitore** [comment]
ammesso e non concesso che escano numeri giusti, non mi sembra un buon modo di fare.
Secondo me è meglio scriverli esplicitamente (magari li metti in un vettore così la stampa diventa più semplice)

**Comment by TeoColuccio** [comment]
Sapevo che non vi sarebbe piaciuto... però bisogna ammettere che era un
signor "Ingiarmo" ahah

Il giorno 16 febbraio 2017 21:14, Fabio Z Tessitore <
notifications@github.com> ha scritto:
